[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
veralux = "4BzWp6JCnguTPGEfHhG12hfJR86tGGU3fJSEdfuo2nBZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./key.json"
